import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { DurableFileOperationService, FILE_CONTENT_TYPES } from './durable-file-operation.js';
import type { FileOperationRecord, FileOperationState } from './platform-file-operation.repository.js';

const roots:string[]=[];
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>fs.rm(root,{recursive:true,force:true})));});
function record(overrides:Partial<FileOperationRecord>={}):FileOperationRecord{return Object.freeze({id:'00000000-0000-4000-8000-000000000001',correlation_id:'00000000-0000-4000-8000-000000000002',principal_id:'00000000-0000-4000-8000-000000000003',operation_kind:'PROMOTION',state:'PREPARED',quarantine_root_key:'MANUFACTURER_QUARANTINE',destination_root_key:'MANUFACTURER_PUBLIC',quarantine_name:'source.upload',destination_name:'target.png',previous_name:null,original_name:'client.png',declared_mime:'image/png',detected_media_type:null,content_sha256:null,size_bytes:null,resource_type:null,resource_id:null,failure_code:null,...overrides});}
async function harness(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'jupiter-file-operation-'));roots.push(root);const transitions:Array<{to:FileOperationState;input:unknown}>=[];const journal={transition:async(_id:string,to:FileOperationState,input:unknown={})=>{transitions.push({to,input});}} as any;return{root,q:path.join(root,'private'),d:path.join(root,'public'),transitions,service:new DurableFileOperationService(journal,fs,{MANUFACTURER_QUARANTINE:path.join(root,'private'),MANUFACTURER_PUBLIC:path.join(root,'public')})};}
const png=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.from('content')]);

describe('L2-2D1 durable file-operation foundation',()=>{
  it('uses UUID server-controlled quarantine and destination names',async()=>{const h=await harness();const q=await h.service.quarantine('MANUFACTURER_QUARANTINE',png);expect(q.name).toMatch(/^[0-9a-f-]{36}\.upload$/);expect(h.service.serverName('image/png')).toMatch(/^[0-9a-f-]{36}\.png$/);});
  it('rejects traversal and unknown roots',async()=>{const h=await harness();await expect(h.service.safeDelete('MANUFACTURER_QUARANTINE','../x')).rejects.toThrow('FILE_OPERATION_BASENAME_REQUIRED');await expect(h.service.quarantine('missing',png)).rejects.toThrow('FILE_OPERATION_ROOT_UNKNOWN');});
  it('validates actual PNG bytes and records digest/size',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);const result=await h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo);expect(result.media).toBe('image/png');expect(result.digest).toHaveLength(64);expect(h.transitions[0]?.to).toBe('VALIDATED');});
  it('rejects declared MIME mismatch and unsupported content',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);await expect(h.service.validate(record({declared_mime:'image/jpeg'}),FILE_CONTENT_TYPES.manufacturerLogo)).rejects.toThrow('FILE_OPERATION_MIME_MISMATCH');await fs.writeFile(path.join(h.q,'source.upload'),Buffer.from('not an image'));await expect(h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo)).rejects.toThrow('FILE_OPERATION_CONTENT_REJECTED');});
  it('validates SB CSV/PDF bytes and rejects a declared-type mismatch',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});const csv=Buffer.from('number,title\nSB-1,Inspection\n');await fs.writeFile(path.join(h.q,'source.upload'),csv);await expect(h.service.validate(record({declared_mime:'text/csv'}),FILE_CONTENT_TYPES.serviceBulletinImport)).resolves.toMatchObject({media:'text/csv'});const pdf=Buffer.from('%PDF-1.4\n%%EOF');await fs.writeFile(path.join(h.q,'source.upload'),pdf);await expect(h.service.validate(record({declared_mime:'application/pdf'}),FILE_CONTENT_TYPES.serviceBulletinImport)).resolves.toMatchObject({media:'application/pdf'});await expect(h.service.validate(record({declared_mime:'text/csv'}),FILE_CONTENT_TYPES.serviceBulletinImport)).rejects.toThrow('FILE_OPERATION_MIME_MISMATCH');});
  it('rejects symlink quarantine sources',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});const outside=path.join(h.root,'outside');await fs.writeFile(outside,png);try{await fs.symlink(outside,path.join(h.q,'source.upload'));}catch{return;}await expect(h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo)).rejects.toThrow('FILE_OPERATION_UNSAFE_SOURCE');});
  it('promotes only validated state through intent and completion',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);const digest=(await h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo)).digest;h.transitions.length=0;const target=await h.service.promote(record({state:'VALIDATED',detected_media_type:'image/png',content_sha256:digest,size_bytes:String(png.length)}));expect(await fs.readFile(target)).toEqual(png);expect(h.transitions.map(v=>v.to)).toEqual(['PROMOTING','PROMOTED']);});
  it('rejects invalid promotion state and an existing destination',async()=>{const h=await harness();await expect(h.service.promote(record())).rejects.toThrow('FILE_OPERATION_NOT_VALIDATED');await fs.mkdir(h.q,{recursive:true});await fs.mkdir(h.d,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);await fs.writeFile(path.join(h.d,'target.png'),png);const digest=(await h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo)).digest;await expect(h.service.promote(record({state:'VALIDATED',content_sha256:digest,size_bytes:String(png.length)}))).rejects.toThrow('FILE_OPERATION_DESTINATION_EXISTS');});
  it('rejects quarantine content changed after validation',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);const valid=await h.service.validate(record(),FILE_CONTENT_TYPES.manufacturerLogo);await fs.writeFile(path.join(h.q,'source.upload'),Buffer.concat([png,Buffer.from('changed')]));await expect(h.service.promote(record({state:'VALIDATED',content_sha256:valid.digest,size_bytes:String(valid.size)}))).rejects.toThrow('FILE_OPERATION_VALIDATION_STALE');expect(h.transitions.map(v=>v.to)).toEqual(['VALIDATED']);});
  it('cleanup is idempotent and rejects symlink deletion',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);expect(await h.service.safeDelete('MANUFACTURER_QUARANTINE','source.upload')).toBe(true);expect(await h.service.safeDelete('MANUFACTURER_QUARANTINE','source.upload')).toBe(false);const outside=path.join(h.root,'outside');await fs.writeFile(outside,png);try{await fs.symlink(outside,path.join(h.q,'source.upload'));}catch{return;}await expect(h.service.safeDelete('MANUFACTURER_QUARANTINE','source.upload')).rejects.toThrow('FILE_OPERATION_UNSAFE_DELETE');expect(await fs.readFile(outside)).toEqual(png);});
  it('recovers interrupted quarantine without promotion',async()=>{const h=await harness();await fs.mkdir(h.q,{recursive:true});await fs.writeFile(path.join(h.q,'source.upload'),png);await expect(h.service.recover(record(),async()=>false)).resolves.toBe('CLEANED');expect(h.transitions.map(v=>v.to)).toEqual(['CLEANUP_REQUIRED','CLEANED']);await expect(fs.stat(path.join(h.q,'source.upload'))).rejects.toMatchObject({code:'ENOENT'});});
  it('recovers a promoted uncommitted file without touching previous committed files',async()=>{const h=await harness();await fs.mkdir(h.d,{recursive:true});await fs.writeFile(path.join(h.d,'target.png'),png);await fs.writeFile(path.join(h.d,'previous.png'),png);await h.service.recover(record({state:'PROMOTED',previous_name:'previous.png'}),async()=>false);await expect(fs.stat(path.join(h.d,'target.png'))).rejects.toMatchObject({code:'ENOENT'});expect(await fs.readFile(path.join(h.d,'previous.png'))).toEqual(png);});
  it('preserves a destination proven committed and never promotes during recovery',async()=>{const h=await harness();await fs.mkdir(h.d,{recursive:true});await fs.writeFile(path.join(h.d,'target.png'),png);await expect(h.service.recover(record({state:'PROMOTED'}),async()=>true)).resolves.toBe('COMMITTED');expect(await fs.readFile(path.join(h.d,'target.png'))).toEqual(png);expect(h.transitions.map(v=>v.to)).toEqual(['COMMITTED']);});
  it('handles crash between promotion intent and journal completion',async()=>{const h=await harness();await fs.mkdir(h.d,{recursive:true});await fs.writeFile(path.join(h.d,'target.png'),png);await h.service.recover(record({state:'PROMOTING'}),async()=>false);await expect(fs.stat(path.join(h.d,'target.png'))).rejects.toMatchObject({code:'ENOENT'});expect(h.transitions.map(v=>v.to)).toEqual(['CLEANUP_REQUIRED','CLEANED']);});
});
