import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { requireManufacturerLogoCommit } from './manufacturer-file-boundary.js';
const read=(value:string)=>readFileSync(value,'utf8');
describe('L2-2D2 Manufacturer HUMAN file boundary',()=>{
  it('gates both mounted routes before CSRF and memory upload parsing',()=>{const policy=read('src/modules/platform-authority/mounted-human-platform-gate.ts');expect(policy).toContain("route(/^\\/manufacturers$/, 'MANUFACTURER_CREATE')");expect(policy).toContain("route(/^\\/manufacturers\\/[^/]+\\/update$/, 'MANUFACTURER_UPDATE')");const routes=read('src/modules/library/library.routes.ts');expect(routes).toMatch(/router\.post\('\/manufacturers', requirePermission\('LIBRARY_EDIT'\), csrfProtection, manufacturerLogoUpload\.single/);expect(routes).toMatch(/router\.post\('\/manufacturers\/:id\/update', requirePermission\('LIBRARY_EDIT'\), csrfProtection, manufacturerLogoUpload\.single/);});
  it('requires file capability exactly when a file is present',()=>{const routes=read('src/modules/library/library.routes.ts');expect(routes).toContain("['MANUFACTURER_CREATE', 'MANUFACTURER_FILE_REPLACE']");expect(routes).toContain("['MANUFACTURER_UPDATE', 'MANUFACTURER_FILE_REPLACE']");const service=read('src/modules/library/library.service.ts');expect(service).toMatch(/createManufacturer[\s\S]*requirePlatformMutationOperations\(evidence, operations\)/);expect(service).toMatch(/updateManufacturer[\s\S]*lock: transaction\.LOCK\.UPDATE[\s\S]*audit\.setBefore/);});
  it('uses D1 lifecycle and never trusts submitted logo_url or durable original names',()=>{const routes=read('src/modules/library/library.routes.ts');expect(routes.slice(routes.indexOf("router.post('/manufacturers'"),routes.indexOf("router.post('/manufacturers/:id/update'"))).not.toContain('logo_url');const boundary=read('src/modules/uploads/manufacturer-file-boundary.ts');for(const value of ['quarantine(','prepare(','validate(','promote(','finishCommitted','recover(','canonicalUploadReference'])expect(boundary).toContain(value);expect(boundary).not.toMatch(/destinationName\s*=.*originalname/);});
  it('rejects caller-fabricated durable logo references',()=>{expect(()=>requireManufacturerLogoCommit({reference:'/uploads/manufacturers/forged.png',operationId:'forged'} as any)).toThrow('MANUFACTURER_LOGO_COMMIT_INVALID');});
  it('journals the authoritative prior logo inside the locked mutation transaction',()=>{const service=read('src/modules/library/library.service.ts');expect(service).toMatch(/lock: transaction\.LOCK\.UPDATE[\s\S]*recordPreviousName\(trustedLogo\.operationId, previousName, transaction\)/);const boundary=read('src/modules/uploads/manufacturer-file-boundary.ts');expect(boundary).toMatch(/if\(!\(await referenced\(newReference\)\)\)return false/);expect(boundary).toMatch(/old&&!await referenced/);expect(boundary.indexOf('input.mutate(issueLogoCommit')).toBeLessThan(boundary.indexOf('finishCommitted(operation,reference)'));});
});
